### ISSUE TITLE
[1.17.1] download url for Linux broken?

### ISSUE THREAD

**Issue by MSandro** [BisUmTo/OpenToALL#5]
```
[11:44:33] [Thread-37/INFO]: [Open to ALL] 
[11:44:33] [Thread-37/ERROR]: [Open to ALL] 
[11:44:33] [Thread-37/INFO]: [STDERR]: java.net.MalformedURLException: no protocol: `https://playit.gg/downloads/playit-linux_64-0.4.4
[11:44:33] [Thread-37/INFO]: [STDERR]: 	at java.base/java.net.URL.<init>(URL.java:674)
[11:44:33] [Thread-37/INFO]: [STDERR]: 	at java.base/java.net.URL.<init>(URL.java:569)
[11:44:33] [Thread-37/INFO]: [STDERR]: 	at java.base/java.net.URL.<init>(URL.java:516)
[11:44:33] [Thread-37/INFO]: [STDERR]: 	at it.multicoredev.opentoall.playit.PlayIt.download(PlayIt.java:68)
[11:44:33] [Thread-37/INFO]: [STDERR]: 	at it.multicoredev.opentoall.playit.PlayIt.run(PlayIt.java:120)
[11:44:33] [Thread-37/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[11:44:33] [Thread-37/ERROR]: [Open to ALL] No file: Impossible to download or find PlayIT app.
[11:44:33] [Thread-37/INFO]: [STDERR]: it.multicoredev.opentoall.playit.PlayIt$PlayItException: No file: Impossible to download or find PlayIT app.
[11:44:33] [Thread-37/INFO]: [STDERR]: 	at it.multicoredev.opentoall.playit.PlayIt.run(PlayIt.java:121)
[11:44:33] [Thread-37/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[11:44:33] [Thread-37/ERROR]: [Open to ALL] 
```

**Comment by 0gp** [comment]
same problem in 1.18.2!
